name: isort
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #ckekout recup le projet
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
      #install les paquets
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort
      #lancer isort sur sa machine
      - name: run isort
        run: python3 -m isort .